# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    
before_install: 
  - sudo apt-get install cmake
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

notifications:
  recipients:
    - nicolas.martin@arobas-music.com
  email:
    on_success: change
    on_failure: always
