
before_install: 
  - sudo apt-get install cmake
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
#  - ctest

#script: cmake -DJSONCPP_LIB_BUILD_SHARED=$SHARED_LIBRARY -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE=$VERBOSE_MAKE . && make
#env:
#  global:
#    - JSONCPP_CONTINUOUS_INTERATION=1
#  matrix:
#    - SHARED_LIBRARY=ON BUILD_TYPE=release VERBOSE_MAKE=false
#    - SHARED_LIBRARY=OFF BUILD_TYPE=release VERBOSE_MAKE=false
#    - SHARED_LIBRARY=OFF BUILD_TYPE=debug VERBOSE VERBOSE_MAKE=true
notifications:
  recipients:
    - nicolas.martin@arobas-music.com
  email:
    on_success: change
    on_failure: always