
before_install: 
  - sudo apt-get install cmake
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

notifications:
  recipients:
    - nicolas.martin@arobas-music.com
  email:
    on_success: change
    on_failure: always
